version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "shunsock"
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "shunsock"

