version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - ./app:/root/opt/app
    working_dir: /root/opt/app/resume_builder
    environment:
      - PYTHONPATH=/root/opt/app/resume_builder/src/resume_builder

