services:
  vitepress:
    image: bunlovesnode/bun:1.0.12-node20.11
    container_name: vitepress
    volumes:
      - ./src:/usr/vitepress/src
      - ./entry_point.sh:/usr/vitepress/entry_point.sh
    working_dir: /usr/vitepress
    command: "tail -f /dev/null"
    ports:
      - "5173:5173"
