name: Build Test

on:
  pull_request:
    branches: ["master"]
    paths:
      - 'docs/**'
      - 'bun.lock'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.0.11

      - name: Install Dependencies
        run: bun install

      - name: Build Site
        run: bash script/build.sh
