name: Build Test

on:
  pull_request:
    branches: ["master"]
    paths:
      - 'docs/**'
      - 'bun.lock'
      - 'flake.nix'
      - 'flake.lock'
      - 'script/*.sh'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build Site
        run: nix run .#build

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './script'
