name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.0.11

      - name: Install Dependencies
        run: bun install
        working-directory: src

      - name: Build Site
        run: bun run docs:build
        working-directory: src

      - name: Copy to /docs Folder
        run: |
          rm -rf ../docs
          mkdir -p ../docs
          cp -R ./docs/.vitepress/dist/* ../docs/

