name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: src

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Setup Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.0.11

      # Step 3: Install Dependencies using Bun
      - name: Install Dependencies
        run: bun install

      # Step 4: Build the site using Bun
      - name: Build Site
        run: bun run docs:build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
      - name: Debug Build Output
        run: ls -R ./docs/.vitepress/dist

