name: Shell Script Validation

on:
  pull_request:
    branches: ["master"]
    paths:
      - '.github/workflows/validate_shellscript.sh'
      - 'script/*.sh'

jobs:
  shellcheck:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './script'
